import { THEME_TEMPLATE_VERSION } from './types';
import type { ThemeMode, ThemeTemplate, ThemeTokens } from './types';

const classicThemeMusicUrl = new URL('../assets/theme-music/classic-one-summer-day.mp3', import.meta.url).href;
const pixelThemeMusicUrl = new URL('../assets/theme-music/pixel-theme-of-sss.mp3', import.meta.url).href;
const opThemeMusicUrl = new URL('../assets/theme-music/op-battle-scars.mp3', import.meta.url).href;

export const DEFAULT_THEME_TEMPLATE_ID = 'pixel-candy';
export const TECH_TEMPLATE_ID = 'tech-default';
export const PIXEL_TEMPLATE_ID = 'pixel-candy';
export const OP_TEMPLATE_ID = 'op-style';

const techDark: ThemeTokens = {
  appBg: '#09090b',
  canvasBg: '#0a0a0b',
  panelBg: '#18181b',
  panelBgElevated: '#27272a',
  panelBgMuted: '#111113',
  nodeBg: 'rgba(24,24,27,0.94)',
  nodeHeaderBg: 'rgba(14,165,233,0.12)',
  textMain: '#f4f4f5',
  textMuted: '#d4d4d8',
  textDim: '#a1a1aa',
  border: 'rgba(255,255,255,0.10)',
  borderStrong: 'rgba(125,211,252,0.45)',
  accent: '#38bdf8',
  accentHover: '#0ea5e9',
  accentText: '#031522',
  secondary: '#a78bfa',
  warning: '#f59e0b',
  danger: '#f87171',
  success: '#34d399',
  shadowPanel: '0 18px 50px rgba(0,0,0,0.42)',
  shadowButton: '0 0 18px rgba(56,189,248,0.18)',
  shadowStrong: '0 24px 70px rgba(0,0,0,0.55)',
  radiusPanel: '14px',
  radiusButton: '8px',
  radiusNode: '12px',
  gridDot: '#27272a',
  edge: '#71717a',
  edgeSelected: '#fb923c',
  selectionBg: 'rgba(14,165,233,0.16)',
  selectionBorder: '#38bdf8',
  portText: '#7dd3fc',
  portImage: '#fcd34d',
  portVideo: '#fda4af',
  portAudio: '#c4b5fd',
  fontFamily: "system-ui, -apple-system, 'PingFang SC', 'Microsoft YaHei', sans-serif",
  displayFont: "system-ui, -apple-system, 'PingFang SC', 'Microsoft YaHei', sans-serif",
};

const techLight: ThemeTokens = {
  ...techDark,
  appBg: '#fafafa',
  canvasBg: '#fafafa',
  panelBg: '#ffffff',
  panelBgElevated: '#f4f4f5',
  panelBgMuted: '#f8fafc',
  nodeBg: 'rgba(255,255,255,0.96)',
  nodeHeaderBg: 'rgba(14,165,233,0.10)',
  textMain: '#18181b',
  textMuted: '#3f3f46',
  textDim: '#71717a',
  border: 'rgba(0,0,0,0.10)',
  borderStrong: 'rgba(2,132,199,0.40)',
  accent: '#0284c7',
  accentHover: '#0369a1',
  accentText: '#ffffff',
  secondary: '#7c3aed',
  warning: '#d97706',
  danger: '#dc2626',
  success: '#059669',
  shadowPanel: '0 18px 45px rgba(15,23,42,0.12)',
  shadowButton: '0 8px 18px rgba(2,132,199,0.18)',
  shadowStrong: '0 24px 70px rgba(15,23,42,0.18)',
  gridDot: '#d4d4d8',
  edge: '#a1a1aa',
  edgeSelected: '#ea580c',
  selectionBg: 'rgba(14,165,233,0.12)',
  selectionBorder: '#0284c7',
};

const pixelLight: ThemeTokens = {
  appBg: '#FAF3E7',
  canvasBg: '#FAF3E7',
  panelBg: '#FFFFFF',
  panelBgElevated: '#FFFFFF',
  panelBgMuted: '#F1E8D5',
  nodeBg: '#FFFFFF',
  nodeHeaderBg: '#A8E6C9',
  textMain: '#1A1410',
  textMuted: '#5C4D3E',
  textDim: '#8B7B68',
  border: '#1A1410',
  borderStrong: '#1A1410',
  accent: '#4ECDC4',
  accentHover: '#A8E6C9',
  accentText: '#1A1410',
  secondary: '#FF89A7',
  warning: '#FFE08A',
  danger: '#FF6B6B',
  success: '#6FD49A',
  shadowPanel: '3px 3px 0 #1A1410',
  shadowButton: '3px 3px 0 #1A1410',
  shadowStrong: '5px 5px 0 #1A1410',
  radiusPanel: '16px',
  radiusButton: '9999px',
  radiusNode: '16px',
  gridDot: '#C8B89A',
  edge: '#1A1410',
  edgeSelected: '#FF89A7',
  selectionBg: 'rgba(168,230,201,0.18)',
  selectionBorder: '#1A1410',
  portText: '#7dd3fc',
  portImage: '#fcd34d',
  portVideo: '#fda4af',
  portAudio: '#c4b5fd',
  fontFamily: "'M PLUS Rounded 1c', 'Noto Sans SC', 'PingFang SC', 'Microsoft YaHei', system-ui, sans-serif",
  displayFont: "'M PLUS Rounded 1c', 'Noto Sans SC', 'PingFang SC', 'Microsoft YaHei', system-ui, sans-serif",
};

const pixelDark: ThemeTokens = {
  ...pixelLight,
  appBg: '#1F1A14',
  canvasBg: '#1F1A14',
  panelBg: '#2A2218',
  panelBgElevated: '#33291d',
  panelBgMuted: '#38301F',
  nodeBg: '#2A2218',
  nodeHeaderBg: '#4ECDC4',
  textMain: '#F5EBD7',
  textMuted: '#C8B89A',
  textDim: '#9E8A69',
  border: '#F5EBD7',
  borderStrong: '#F5EBD7',
  accent: '#4ECDC4',
  accentHover: '#A8E6C9',
  accentText: '#1F1A14',
  secondary: '#FF89A7',
  warning: '#5A4519',
  danger: '#9D2E2E',
  success: '#1F6E45',
  shadowPanel: '3px 3px 0 #F5EBD7',
  shadowButton: '3px 3px 0 #F5EBD7',
  shadowStrong: '5px 5px 0 #F5EBD7',
  gridDot: '#5C4D3E',
  edge: '#F5EBD7',
  edgeSelected: '#FFB5C5',
  selectionBg: 'rgba(78,205,196,0.18)',
  selectionBorder: '#F5EBD7',
};

const opLight: ThemeTokens = {
  appBg: '#f4e2b3',
  canvasBg: '#efd59a',
  panelBg: '#fff3cf',
  panelBgElevated: '#fff9df',
  panelBgMuted: '#e6c77f',
  nodeBg: '#fff3cf',
  nodeHeaderBg: '#f2c94c',
  textMain: '#2b1b10',
  textMuted: '#5e3b22',
  textDim: '#84613b',
  border: '#2b1b10',
  borderStrong: '#2b1b10',
  accent: '#0f7c8c',
  accentHover: '#0b6572',
  accentText: '#ffffff',
  secondary: '#c82828',
  warning: '#f2c94c',
  danger: '#b51f1f',
  success: '#168a55',
  shadowPanel: '4px 4px 0 #2b1b10',
  shadowButton: '3px 3px 0 #2b1b10',
  shadowStrong: '6px 6px 0 #2b1b10',
  radiusPanel: '14px',
  radiusButton: '9999px',
  radiusNode: '14px',
  gridDot: '#9c7b45',
  edge: '#2b1b10',
  edgeSelected: '#c82828',
  selectionBg: 'rgba(15,124,140,0.20)',
  selectionBorder: '#2b1b10',
  portText: '#0f7c8c',
  portImage: '#d99b16',
  portVideo: '#c82828',
  portAudio: '#4b4aa3',
  fontFamily: "'M PLUS Rounded 1c', 'Noto Sans SC', 'PingFang SC', 'Microsoft YaHei', system-ui, sans-serif",
  displayFont: "'M PLUS Rounded 1c', 'Noto Sans SC', 'PingFang SC', 'Microsoft YaHei', system-ui, sans-serif",
};

const opDark: ThemeTokens = {
  ...opLight,
  appBg: '#071421',
  canvasBg: '#0a1b2e',
  panelBg: '#14253b',
  panelBgElevated: '#1e3552',
  panelBgMuted: '#20385c',
  nodeBg: '#14253b',
  nodeHeaderBg: '#5b3f16',
  textMain: '#fff4d0',
  textMuted: '#dcc98d',
  textDim: '#a8a07d',
  border: '#fff4d0',
  borderStrong: '#fff4d0',
  accent: '#1b8fa0',
  accentHover: '#26b8c6',
  accentText: '#06121d',
  secondary: '#8f2d2d',
  warning: '#5b3f16',
  danger: '#7f1d1d',
  success: '#0f5c3f',
  shadowPanel: '4px 4px 0 #fff4d0',
  shadowButton: '3px 3px 0 #fff4d0',
  shadowStrong: '6px 6px 0 #fff4d0',
  gridDot: '#315276',
  edge: '#fff4d0',
  edgeSelected: '#ff6b4a',
  selectionBg: 'rgba(38,184,198,0.22)',
  selectionBorder: '#fff4d0',
  portText: '#58d4e0',
  portImage: '#d99b16',
  portVideo: '#ff6b4a',
  portAudio: '#9f8cff',
};

export const BUILT_IN_THEME_TEMPLATES: ThemeTemplate[] = [
  {
    schema: 't8-theme-template',
    version: THEME_TEMPLATE_VERSION,
    id: TECH_TEMPLATE_ID,
    name: '科技风',
    description: '玻璃拟态、细边框、冷色发光的默认科技视觉。',
    author: 'T8',
    builtIn: true,
    legacyStyle: 'tech',
    visuals: {
      style: 'tech',
      intensity: 'medium',
      iconPack: 'default',
      canvasPattern: 'circuit',
      nodeFrame: 'glass',
      headerMark: '科技',
    },
    music: {
      title: "One Summer's Day",
      preset: 'tech-pulse',
      source: 'url',
      url: classicThemeMusicUrl,
      volume: 0.16,
      bpm: 112,
      copyrightNote: '经典主题默认音乐文件，可在主题模板中上传替换。',
    },
    modes: { dark: { tokens: techDark }, light: { tokens: techLight } },
  },
  {
    schema: 't8-theme-template',
    version: THEME_TEMPLATE_VERSION,
    id: PIXEL_TEMPLATE_ID,
    name: '像素糖果风',
    description: '奶油底、黑描边、糖果色块和硬阴影。',
    author: 'T8',
    builtIn: true,
    legacyStyle: 'pixel',
    visuals: {
      style: 'pixel',
      intensity: 'medium',
      iconPack: 'default',
      canvasPattern: 'dots',
      nodeFrame: 'sticker',
      headerMark: '像素',
    },
    music: {
      title: 'Theme Of SSS',
      preset: 'pixel-pop',
      source: 'url',
      url: pixelThemeMusicUrl,
      volume: 0.15,
      bpm: 128,
      copyrightNote: '像素风默认音乐文件，可在主题模板中上传替换。',
    },
    modes: { dark: { tokens: pixelDark }, light: { tokens: pixelLight } },
  },
  {
    schema: 't8-theme-template',
    version: THEME_TEMPLATE_VERSION,
    id: OP_TEMPLATE_ID,
    name: 'OP风格',
    description: 'One Piece 航海冒险视觉：悬赏令、海图、草帽旗帜、赤红海蓝与金币金。',
    author: 'T8',
    builtIn: true,
    legacyStyle: 'pixel',
    visuals: {
      style: 'op',
      intensity: 'medium',
      iconPack: 'op',
      canvasPattern: 'map',
      nodeFrame: 'wanted',
      headerMark: 'ONE PIECE',
    },
    music: {
      title: 'Battle Scars',
      preset: 'grand-line-adventure',
      source: 'url',
      url: opThemeMusicUrl,
      volume: 0.16,
      bpm: 96,
      copyrightNote: 'OP 风格默认音乐文件，可在主题模板中上传替换。',
    },
    modes: { dark: { tokens: opDark }, light: { tokens: opLight } },
  },
];

export function resolveThemeTemplate(
  templateId?: string,
  customTemplates: ThemeTemplate[] = [],
): ThemeTemplate {
  return (
    customTemplates.find((tpl) => tpl.id === templateId) ||
    BUILT_IN_THEME_TEMPLATES.find((tpl) => tpl.id === templateId) ||
    BUILT_IN_THEME_TEMPLATES.find((tpl) => tpl.id === DEFAULT_THEME_TEMPLATE_ID) ||
    BUILT_IN_THEME_TEMPLATES[0]
  );
}

export function getTemplateMode(template: ThemeTemplate, mode: ThemeMode) {
  return template.modes[mode] || template.modes.light || template.modes.dark;
}
